### ISSUE TITLE
MADA Module 5 feedback

### ISSUE THREAD

**Issue by nicole-luisi** [yl3362/yaolu-MADA-portfolio#3]
Hi Yao. Great job with this visualization! A few things you could consider:
- [Not related to the graphic, but if you use `#| warning: false` in your code chunk where you load the packages it keeps the warning message text out of your output!] 
- [In the first plot, it looks like the x-axis labels repeat and are a bit too long to fit in the grid view. You might be able to get it closer to the original image if you remove the x-axis labels from all but the NFL graphic in the middle, that might make it look like there is just one x-axis label centered for all.] 
- [Also on the first plot, I think geom_smooth might support having different colors for each line similar to the original plot. I know for geom_point you can specify `colour`, not sure if you tried this for the lines.] 
- [The 2nd plot looks very similar, could just swap that green color out for gray to make it more like the original! You would probably have to make a custom palette with the hexcodes, but it's not too bad to apply these to factor variables like you are using here!]

**Comment by yl3362** [comment]
Thank you. I will try to use #| warning: false to simplify the website. I will see if I can make the x-axis labels better. Thanks for sharing the colour command. I will see if we can use it in both geom_smooth from 1st plot and barplot from 2nd plot.
